"""Global config cho project."""
GAP_THRESHOLD_DAYS = 7
INTERPOLATE_LIMIT_HOURS = 3
FFILL_LIMIT_HOURS = 3
TRAIN_RATIO = 0.80
VAL_RATIO = 0.10
TEST_RATIO = 0.10
IQR_MULTIPLIER = 1.5
RANDOM_STATE = 42
TARGET = "pm25"
